# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.network "forwarded_port", guest: 5432, host: 5433

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.become = true
  end
end
